(** Representation of game play map.

    This module represents the data stored in map files. It handles loading of
    that data from JSON as well as querying the data. *)

type t
(** The abstract type of values representing adventures. *)

type obj = {
  id : int;
  name : string;
  obj_class : string;
  height : int;
  width : int;
  x : int;
  y : int;
}
(** The type representing an object on a map. *)

exception UnknownRoom of string
(** Raised when an unknown room identifier is encountered. It carries the
    identifier of the unknown room. *)

exception UnknownExit of string
(** Raised when an unknown exit is encountered. It carries the name of the
    unknown exit. *)

val from_json : Yojson.Basic.t -> t
(** [from_json j] is the room that [j] represents. Requires: [j] is a valid JSON
    tilemap generated by Tiled. *)

val spawn : t -> obj
(** [spawn t] is the identifier of the starting room in adventure [a]. Example:
    the [start_room] of Cornell Campus Battle is ["Feeney Way"]. *)

val description : t -> string -> string
(** [description a r] is the description of the room with identifier [r] in
    adventure [a]. Raises [UnknownRoom r] if [r] is not a room identifier in
    [a]. Example: in Ho Plaza, the [description] of room identifier
    ["Feeney Way"] begins with ["You are on Feeney Way. "] *)

val dirs : t -> string -> string list
(** [dirs a r] is a set-like list of all valid directions from the room with
    identifier [r] in adventure [a]. Raises [UnknownRoom r] if [r] is not a room
    identifier in [a]. *)

val next_room : t -> string -> string -> string
(** [next_room a r e] is the identifier of the room in adventure [a] that is
    immediately reached by taking the exit named [e] from the room with
    identifier [r]. Raises [UnknownRoom r] if [r] is not a room identifier in
    [a]. Raises [UnknownExit e] if [e] is not the name of a cardinal direction
    (["north"], ["south"], ["east"], or ["west"]). *)

val next_rooms : t -> string -> string list
(** [next_rooms a r] is a set-like list of all the identifiers of rooms in
    adventure [a] that are immediately reachable by taking any exit from the
    room with identifier [r]. Raises [UnknownRoom r] if [r] is not a room
    identifier in [a]. *)
