(** Representation of tileset data.

    This module represents the data stored in tileset files. It handles loading
    of that data from the JSON as well as querying of the data, and includes
    useful functions for tilemaps to extract data from tilesets.*)

type t
(**The abstract type representing tileset data.*)

val load_tileset : string -> Tsdl.Sdl.renderer -> int -> t
(**[load_tileset fl ren fgid] is the tileset contained in the JSON file [fl];
   the GID of its first tile is [fgid]. Renderer [ren] is used to generate the
   associated texture. Requires: [fl] is a well-formed JSON tileset file
   generated by Tiled.*)

val get_tile : t -> int -> Tsdl.Sdl.rect
(**[get_tile tset id] is the [Tsdl.Sdl.rect] containing the tile specified by
   [gid] in the image associated with [tset].*)

val get_tex : t -> Tsdl.Sdl.texture
(**[get_tex tset] is the [Tsdl.Sdl.texture] associated with [tset].*)

val get_colliders : t -> int list
(**[get_colliders tset] is the list of [gids] associated with collidable tiles
   in [tset].*)
