(** Representation of tilemap data.

    This module represents the data stored in tilemap files. It handles loading
    of that data from JSON as well as querying the data.*)

type t
(**The abstract type representing tilemap data.*)

val load_map : string -> Tsdl.Sdl.renderer -> t
(**[load_map fl ren] creates a new tilemap representation, with map data from
   the JSON file [fl]. This is done using renderer [ren]. Requires: [fl] is a
   well-formed JSON file generated by Tiled. *)

val draw_map : t -> Tsdl.Sdl.renderer -> unit
(**[draw_map m ren] draws the tilemap [m] onscreen using renderer [ren]. *)

val get_spawn : t -> int * int
(**[get_spawn m] is the coordinates of the spawn point on map [m].*)

val scale : t -> int
(**[scale m] is the ratio of the global tile size that is rendered onscreen and
   the tile size of [m], as in the image file supplying its tile textures.

   Example: If the tile textures for [m] are 16 by 16 pixels and the tiles
   rendered onscreen are 32 by 32 pixels, [scale m] is 2.*)
