lib: [
  "_build/install/default/lib/Lib/META"
  "_build/install/default/lib/Lib/dune-package"
  "_build/install/default/lib/Lib/fmts.ml"
  "_build/install/default/lib/Lib/lib.a"
  "_build/install/default/lib/Lib/lib.cma"
  "_build/install/default/lib/Lib/lib.cmi"
  "_build/install/default/lib/Lib/lib.cmt"
  "_build/install/default/lib/Lib/lib.cmx"
  "_build/install/default/lib/Lib/lib.cmxa"
  "_build/install/default/lib/Lib/lib.ml"
  "_build/install/default/lib/Lib/lib__Fmts.cmi"
  "_build/install/default/lib/Lib/lib__Fmts.cmt"
  "_build/install/default/lib/Lib/lib__Fmts.cmx"
  "_build/install/default/lib/Lib/opam"
]
libexec: [
  "_build/install/default/lib/Lib/lib.cmxs"
]
doc: [
  "_build/install/default/doc/Lib/README.md"
]
